# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false 

# Setup
title:               Lincon Dias
tagline:             'Salvando a vida do full-stack(overflow)'
description:         'Fundador da <a href="http://emptybits.com.br" target="_blank">EmptyBits</a>, colaborador na <a href="http://level5jr.com.br" target="_blank">Level5</a> e estudante de sistemas de informação na Universidade Federal de Goiás.'
url:                 http://lincond.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Lincon Dias
  url:               https://emptybits.com.br
  email:             lincon@emptybits.com.br

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
